Sure, here is the content in markdown:

---

By definition, this is also the Maclaurin series for cos \(x\). In Section 8.10, we see that the series converges to cos \(x\) at every \(x\).

Because \( f^{(2n+1)}(0) = 0 \), the Taylor polynomials of orders \(2n\) and \(2n+1\) are identical:

\[ P_{2n}(x) = P_{2n+1}(x) = 1 - \frac{x^2}{2!} + \frac{x^4}{4!} - \cdots + (-1)^n \frac{x^{2n}}{(2n)!} \]

Figure 8.18 shows how well these polynomials approximate \( f(x) = \cos(x) \) near \( x = 0 \). Only the right-hand portions of the graphs are given because the graphs are symmetric about the y-axis.

**EXAMPLE 4**: A function \( f \) whose Taylor series converges at every \(x\) but converges to \( f(x) \) only at \( x = 0 \)

It can be shown (though not easily) that

\[ f(x) = \begin{cases} 
0, & x = 0 \\ 
e^{-1/x^2}, & x \neq 0 
\end{cases} \]

(Fig. 8.19) has derivatives of all orders at \( x = 0 \) and that \( f^{(n)}(0) = 0 \) for all \( n \). This means that the Taylor series generated by \( f \) at \( x = 0 \) is

\[ f(0) + f'(0)x + \frac{f''(0)}{2!}x^2 + \cdots + \frac{f^{(n)}(0)}{n!}x^n + \cdots \]
\[ = 0 + 0 \cdot x + 0 \cdot x^2 + \cdots + 0 \cdot x^n + \cdots \]
\[ = 0 + 0 + \cdots + 0 + \cdots \]

The series converges for every \( x \) (its sum is 0) but converges to \( f(x) \) only at \( x = 0 \).

Two questions still remain.

1. For what values of \( x \) can we normally expect a Taylor series to converge to its generating function?

---

